version: '3.9'
services:
  nextjudge-frontend:
    extends: 
      file: src/web/docker-compose.yml
      service: nextjudge-frontend

  nextjudge-bridge:
    extends: 
      file: src/bridge/docker-compose.yml
      service: nextjudge-bridge
    environment:
      - DATABASE_HOST=nextjudge-data-layer
    depends_on:
      - nextjudge-data-layer
      
  nextjudge-data-layer:
    extends: 
      file: src/data-layer/docker-compose.yml
      service: nextjudge-data-layer
  

  nextjudge-judge:
    extends: 
      file: src/judge/docker-compose.yml
      service: nextjudge-judge
      environment:
        - BRIDGE_HOST=nextjudge-bridge # This override is not working - bug in Docker compose?
        - BRIDGE_PORT=3000
  
  redis:
    extends: 
      file: src/bridge/docker-compose.yml
      service: redis

  db:
    extends: 
      file: src/data-layer/docker-compose.yml
      service: db
      
      
volumes: 
  postgres_data:
  
  