services:

  nextjudge-data-layer-dev:
    extends: 
      file: src/data-layer/docker-compose.dev.yml
      service: nextjudge-data-layer-dev
    environment:
      - ELASTIC_ENDPOINT=http://elasticsearch:9200
      - ELASTIC_ENABLED="${ELASTIC_ENABLED:-false}"
      - JUDGE_PASSWORD=${JUDGE_PASSWORD}
      - JWT_SIGNING_SECRET=${JWT_SIGNING_SECRET}
      - AUTH_PROVIDER_PASSWORD=${AUTH_PROVIDER_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      # elasticsearch:
    #     # condition: service_healthy

  db:
    extends: 
      file: src/data-layer/docker-compose.db.yml
      service: db

  nextjudge-judge-dev:
    extends: 
      file: src/judge/docker-compose.dev.yml
      service: nextjudge-judge-dev
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - NEXTJUDGE_HOST=nextjudge-data-layer-dev
      - NEXTJUDGE_PORT=5000
      - JUDGE_PASSWORD=${JUDGE_PASSWORD}
    profiles: [judge]
    depends_on:
      rabbitmq:
        condition: service_healthy
      nextjudge-data-layer-dev:
        condition: service_healthy

  rabbitmq:
    extends: 
      file: src/data-layer/docker-compose.rabbitmq.yml
      service: rabbitmq
    environment:
      - RABBITMQ_LOGS="error"

  # elasticsearch:
  #   extends:
  #     file: src/data-layer/docker-compose.elasticsearch.yml
  #     service: elasticsearch
  #   profiles: [elastic]

volumes: 
  postgres_data:
  
  