services:

  nextjudge-data-layer:
    extends: 
      file: src/data-layer/docker-compose.go.yml
      service: nextjudge-data-layer
    environment:
      - ELASTIC_ENDPOINT=http://elasticsearch:9200
      - ELASTIC_ENABLED="${ELASTIC_ENABLED:-false}"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      # elasticsearch:
      #   condition: service_healthy
  db:
    extends: 
      file: src/data-layer/docker-compose.db.yml
      service: db

  nextjudge-judge:
    extends: 
      file: src/judge/docker-compose.yml
      service: nextjudge-judge
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - NEXTJUDGE_HOST=nextjudge-data-layer
      - NEXTJUDGE_PORT=5000
    depends_on:
      rabbitmq:
        condition: service_healthy
      # No Docker healthcheck in prod container
      # nextjudge-data-layer:
      #   condition: service_healthy
  
  rabbitmq:
    extends: 
      file: src/data-layer/docker-compose.rabbitmq.yml
      service: rabbitmq
    environment:
      - RABBITMQ_LOGS="error"

  # elasticsearch:
  #   extends:
  #     file: src/data-layer/docker-compose.elasticsearch.yml
  #     service: elasticsearch

volumes: 
  postgres_data:
  
  