FROM golang:1.25.1-alpine AS build-stage
WORKDIR /app


RUN go install github.com/air-verse/air@latest


COPY go.mod go.sum ./
RUN go mod download

RUN mkdir /config
COPY <<EOF /config/.air.toml
root = "."
watch_dir = "src"
[build]
cmd = "go build -o ./tmp/main ./src"
bin = "tmp/main"
args = ["-d"]
EOF


EXPOSE 5000

ENTRYPOINT ["air", "-c", "/config/.air.toml"]
