services:
  nextjudge-data-layer:
    extends:
      file: docker-compose.go.yml
      service: nextjudge-data-layer
    depends_on:
      db:
        condition: service_healthy
  db:
    extends:
      file: docker-compose.db.yml
      service: db
  elasticsearch:
    extends:
      file: docker-compose.elasticsearch.yml
      service: elasticsearch

volumes:
  postgres_data: