version: '3.9'
services:
  nextjudge-data-layer:
    extends:
      file: docker-compose.go.yml
      service: nextjudge-data-layer
    depends_on:
      db:
        condition: service_healthy
  db:
    extends:
      file: docker-compose.db.yml
      service: db

volumes:
  postgres_data: