services:
  nextjudge-data-layer:
    build: .
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
    healthcheck:
      test: ["CMD", "/main", "-healthcheck", "-p", "5000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
