services:
  nextjudge-data-layer:
    build: .
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
    # wget is not in the container, so this silently fails
    # healthcheck:
    #   test: "wget localhost:5000/healthy -q -O - > /dev/null 2>&1"
    #   interval: 3s
    #   timeout: 3s
    #   retries: 20
