VERSION 0.6

deps:
    FROM golang:latest
    WORKDIR /services/engine
    COPY ../../libs/calculator+artifact/* /libs/calculator
    COPY go.mod go.sum ./
    RUN go mod download

compile:
    FROM +deps
    COPY main.go .
    RUN go build -o engine main.go

unit-test:
    FROM +compile
    COPY main_test.go .
    RUN CGO_ENABLED=0 go test -v

docker:
    FROM +compile
    ENTRYPOINT ["./engine"]
    SAVE IMAGE engine:latest