# version: '3.9'
services:
  nextjudge-bridge:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5000
      - JWT_SECRET=this_is_purely_for_testing_CHANGE_THIS_IN_PROD
    extra_hosts:
      - "host.docker.internal:host-gateway"
    init: true

  redis:
    image: redis
    ports:
      - "6379:6379"
      - "16379:16379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5