# version: '3.9'
services:
  nextjudge-bridge:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    init: true # Make ctrl-c actual stop it immediately

  redis:
    image: redis
    ports:
      - "6379:6379"
      - "16379:16379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5