services:
  nextjudge-bridge:
    build:
      context: .
      target: prod
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5000
      - JWT_SECRET=this_is_purely_for_testing_CHANGE_THIS_IN_PROD
    extra_hosts:
      - "host.docker.internal:host-gateway"
    init: true

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 2s
      timeout: 3s
      retries: 5