services:
  nextjudge-bridge:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5000
      - JWT_SECRET=this_is_purely_for_testing_CHANGE_THIS_IN_PROD
    extra_hosts:
      - "host.docker.internal:host-gateway"
    init: true
    volumes:
      - ./src/:/app/src/:ro
      - ./tsconfig.json:/app/tsconfig.json:ro

  redis:
    image: redis
    ports:
      - "6379:6379"
      - "16379:16379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 2s
      timeout: 3s
      retries: 5