FROM nextjudge-judge-test-dev

WORKDIR /app

RUN mkdir -p /app/src/
RUN ln -s /app/languages.toml /app/src/languages.toml
# RUN touch /app/src/__init__.py

COPY test-requirements.txt ./
RUN pip install -r test-requirements.txt --break-system-packages

COPY tests ./tests
RUN touch /app/tests/__init__.py

# CMD ["ls", "-pla"]
ENV PYTEST_ADDOPTS="--color=yes"
ENTRYPOINT [ "pytest", "-v", "-l" ]

